apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dublin-rolebinding
  namespace: dublin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-dublin
    namespace: config-management-system
