apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: dublin
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://networkagent:{{ lookup('env', 'WEBAPPS_PWD') }}@{{external_ip_address}}:3000/networkagent/dublin
    revision: HEAD
    branch: master
    auth: none
    gcpServiceAccountEmail: networkagent@me.com
    noSSLVerify: True
