apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: locations-rolebinding
  namespace: locations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-locations
    namespace: config-management-system
