apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: locations
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://networkagent:password123@{{external_ip_address}}:3000/networkagent/locations
    revision: HEAD
    branch: master
    auth: none
    gcpServiceAccountEmail: networkagent@me.com
    noSSLVerify: True
