apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: london-rolebinding
  namespace: london
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-london
    namespace: config-management-system
