- hosts: edges
  tasks:
  - name: discover network
    delegate_to: localhost
    import_role:
      name: discover

  # - name: run install
  #   import_role:
  #     name: install


  # - name: run wireguard
  #   become: yes
  #   ansible.builtin.systemd_service:
  #     state: restarted
  #     enabled: true
  #     name: wg-quick@wg0
