apiVersion: google.dev/v1
kind: PointToPointService
metadata:
  name: ptpservice1
  labels:
    customer: acme
    graph: "true"
spec:
  interfaces: # the "remote" customer subnets to connect
    - london
    - sydney
