apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf
  labels:
    app: free5gc
    nf: amf
    graph: "true"
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: amf
    spec:
      initContainers:
      - name: wait-nrf
        image: appropriate/curl
        env:
        - name: DEPENDENCIES
          value: nrf-nnrf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the NRF; sleep 2; done;"]
      containers:
      - image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/amf:latest
        imagePullPolicy: Always
        name: amf
        ports:
        - name: namf
          containerPort: 8000
        - name: n2
          containerPort: 38412
          protocol: SCTP
        command: ["./amf"]
        args: ["--config", "config/amfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: amf-volume
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: amf-volume
        projected:
          sources:
          - configMap:
              name: amf-configmap
