- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: install base apt packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates 
      - gnupg-agent
      - apt-transport-https 
      - software-properties-common
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - docker-compose-plugin
      - containerd.io
    state: latest
    update_cache: true

- name: Check if netbox already there
  ansible.builtin.stat:
    path: /opt/netbox-docker
  register: netboxdocker

- name: clone netbox docker
  command: git clone -b release https://github.com/netbox-community/netbox-docker.git
  args:
    chdir: /opt
  when: not netboxdocker.stat.exists 

# - name: update ports
# tee docker-compose.override.yml <<EOF
# services:
#   netbox:
#     ports:
#       - 8000:8080
# EOF

- name: docker compose up 
  community.docker.docker_compose_v2:
    project_src: /opt/netbox-docker
    state: present 