apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshservices.google.dev
  # labels:
  #   type: connectivityservice
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: MeshService
    plural: meshservices
    singular: meshservice
    shortNames:
      - mesh
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                interfaces:
                  description: |
                    Between two and ten customer VPC Subnetwork locations to be connected together with a mesh VPN.

                    All locations will be able to route traffic to each other. There must be no overlapping 
                    IP address ranges across each of the locations.
                  type: array
                  items:
                    type: string
                  oneOf:
                    - minItems: 2
                      maxItems: 10
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true