apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxs.google.dev
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: Nginx
    plural: nginxs
    singular: nginx
    shortNames:
      - nginx
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                interface: 
                  description: The network interface
                  type: object
                  properties:
                    name:
                      description: name of the vpc
                      type: string
                    namespace:
                      description: name of the vpc namespace
                      type: string
                address: 
                  description: The address to assign
                  type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true