apiVersion: google.dev/v1
kind: WireguardAppliance
metadata:
  name: wg1
spec:
  vmname: edge1
  tunnelSubnet: 192.168.1.0/24
  tunnelAddress: 192.168.1.1
  allowedInterface: site2-dev
  peer: edge2
---
apiVersion: google.dev/v1
kind: WireguardAppliance
metadata:
  name: wg2
spec:
  vmname: edge2
  tunnelSubnet: 192.168.1.0/24
  tunnelAddress: 192.168.1.2
  allowedInterface: site1-dev
  peer: edge1
