# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0
info:
  title: Deploy Network API
  description: API for triggering a network delpoyment
  version: 1.0.0

servers:
  - url: https://network-agent-api-4q7fdnlzwa-nw.a.run.app/ui/ui   

paths:
  /:
    post:
      summary: Deploy Network
      description: Takes App Name and Location
      operationId: helloHttp 
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deployNetworkSchema' 
      responses:
        '200':
          description: Successful translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deployNetworkSchemaResponse'
        # ... other error responses 

components:
  schemas:
    deployNetworkSchema:
      type: object
      properties:
        sessionInfo:
          type: object
          properties:
            parameters:
              type: object
              properties:
                appName:
                  type: string
                location:
                  type: string
    deployNetworkSchemaResponse:
      type: object
      properties:
        sessionInfo:
          type: object
          properties:
            parameters:
              type: object
              properties:
                deploymentStatus:
                  type: object
                  properties:
                    results:
                      type: array
                      items:
                        type: array
                        items:
                          type: string
                    networkID:
                      type: string
                    status: 
                      type: string