- name: install wireguard
  become: True
  ansible.builtin.apt:
    name: 
     - wireguard
     - python3-pip
    state: present

- name: set ip forwarding
  become: True
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    reload: true

- name: generate server config
  become: True
  template:
    src: server.conf
    dest: /etc/wireguard/wg0.conf
