[Interface]
PrivateKey = {{ wgKeys[inventory_hostname]['privateKey'] }}
Address = {{ tunnel_address }}
# PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ default_interface }} -j MASQUERADE
# PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ default_interface }} -j MASQUERADE
ListenPort = 51820

[Peer]
PublicKey = {{ wgKeys[peer_name]['publicKey'] }}
AllowedIPs = {{ interface_cidr }}, {{ tunnel_cidr }}
Endpoint = {{ peer_ip_address }}:51820
