[Interface]
PrivateKey = {{ hostvars[inventory_hostname].wgKeys[inventory_hostname]['privateKey'] }}
Address = {{ tunnelAddress }}
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ defaultInterface }} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ defaultInterface }} -j MASQUERADE
ListenPort = 51820

[Peer]
PublicKey = {{ hostvars[inventory_hostname].wgKeys[hostvars[inventory_hostname]['peer']]['publicKey'] }}
AllowedIPs = {{ interface_cidr }}
Endpoint = {{ peer_ip_address }}:51823
