---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: internet-dnn
  labels:
    customer: acme
    graph: "true"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: internet-dnn
  labels:
    graph: "true"
spec:
  ipCidrRange: 172.168.0.0/24
  region: "{{GOOGLE_REGION}}"
  description: internet DNN Network
  networkRef:
    name: internet-dnn
    namespace: london
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: internet-dnn
  labels:
    customer: acme
    graph: "true"
spec:
  allow:
    - protocol: tcp
      ports:
       - "0-65535"
    - protocol: udp
      ports:
       - "0-65535"
    - protocol: icmp
  networkRef:
    name: internet-dnn
    namespace: london
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
