---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: london
  labels:
    customer: acme
    graph: "true"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: london
  labels:
    customer: acme
    graph: "true"
spec:
  ipCidrRange: 10.0.50.0/24
  region: "{{GOOGLE_REGION}}"
  description: london Network
  networkRef:
    name: london
    namespace: london
  secondaryIpRange:
  - rangeName: servicesrange
    ipCidrRange: 10.3.0.0/16
  - rangeName: clusterrange
    ipCidrRange: 10.4.0.0/16
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: london-allowed
  labels:
    customer: acme
    graph: "true"
spec:
  allow:
    - protocol: tcp
      ports:
       - "0-65535"
    - protocol: udp
      ports:
       - "0-65535"
    - protocol: icmp
  networkRef:
    name: london
    namespace: london
  direction: INGRESS\
  priority: 500
  sourceRanges:
    - 0.0.0.0/0
