# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: london-cluster-ip-lb
spec:
  addressType: INTERNAL
  description: a shared IP for london cluster internal load balancer
  location: "{{GOOGLE_REGION}}"
  purpose: SHARED_LOADBALANCER_VIP
  subnetworkRef:
    name: london
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{GOOGLE_PROJECT}}
  name: london-cluster-feature-membership
spec:
  projectRef:
    name: {{GOOGLE_PROJECT}}
  location: global
  membershipRef:
    name: london-cluster-membership
  featureRef:
    name: london-cluster-feature
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: "ssh://git@{{external_ip_address}}:2022/networkagent/london-cluster.git"
        syncBranch: "master"
        secretType: "ssh"
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: london-cluster-feature
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  projectRef:
    name: {{GOOGLE_PROJECT}}
  location: global
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: london-cluster-membership
spec:
  location: global
  authority:
    issuer: https://container.googleapis.com/v1/projects/{{GOOGLE_PROJECT}}/locations/{{GOOGLE_REGION}}/clusters/london-cluster
  description: London Cluster GKE Hub membership
  endpoint:
    gkeCluster:
      resourceRef:
        name: london-cluster
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: london-cluster
  annotations:
    cnrm.cloud.google.com/project-id: {{GOOGLE_PROJECT}}
  labels:
    graph: "true"
spec:
  description: London Cluster
  enableAutopilot: false
  enableLegacyAbac: true
  location: "{{GOOGLE_REGION}}"
  initialNodeCount: 4
  defaultMaxPodsPerNode: 16
  enableL4IlbSubsetting: true
  nodeConfig:
    machineType: n1-standard-4
    diskSizeGb: 100
    diskType: pd-standard
    preemptible: false
    minCpuPlatform: "Intel Haswell"
    imageType: "ubuntu_containerd"
  releaseChannel:
    channel: STABLE
  workloadIdentityConfig:
    workloadPool: "{{GOOGLE_PROJECT}}.svc.id.goog"
  networkingMode: VPC_NATIVE
  ipAllocationPolicy:
    servicesSecondaryRangeName: servicesrange
    clusterSecondaryRangeName: clusterrange
  networkRef:
    name: london
    namespace: london
  subnetworkRef:
    name: london
    namespace: london
  nodeLocations:
    - "{{GOOGLE_ZONE}}"
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: {{GOOGLE_PROJECT}}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
spec:
  name: {{GOOGLE_PROJECT}}
  organizationRef:
    external: "{{GOOGLE_ORG_NAME}}"

---
apiVersion: google.dev/v1
kind: GitCertificate
metadata:
  name: london-gitcert
spec:
  cluster: 
    name: london-cluster
    namespace: london
