# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
    client.lifecycle.config.k8s.io/mutation: ignore
  name: london-app1
  labels:
    customer: acme
    graph: "true"
spec:
  machineType: e2-standard-2
  zone: {{GOOGLE_ZONE}}
  bootDisk:
    initializeParams:
      size: 50
      type: pd-ssd
      sourceImageRef:
        external: ubuntu-os-cloud/ubuntu-2204-lts
  networkInterface:
    - subnetworkRef:
        external: "https://www.googleapis.com/compute/v1/projects/{{GOOGLE_PROJECT}}/regions/{{GOOGLE_REGION}}/subnetworks/mgmt-subnet"
    - subnetworkRef:
        name: london
  canIpForward: true
  metadataStartupScript: "sudo apt-get update;sudo apt-get install -yq python3;sudo ip route add 10.0.40.0/24 via 10.0.50.1;sudo ip route add 10.0.70.0/24 via 10.0.50.1;sudo ip route add 10.0.60.0/24 via 10.0.50.1;sudo ip route add 10.0.80.0/24 via 10.0.50.1"
  metadata:
    - key: ssh-keys
      value: {{GOOGLE_VM_USER}}:{{GOOGLE_SSH_KEY}}
