# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create london cluster repo directory
  file:
    path: /opt/london-cluster-repo
    state: directory
    owner: git
    group: git
    mode: 0775

- name: init git repo
  command: sudo -u git git init
  args:
    chdir: /opt/london-cluster-repo

- name: configure git user name
  command: "sudo -u git git config --global user.name 'Network Agent'"
  args:
    chdir: /opt/london-cluster-repo

- name: configure git email
  command: "sudo -u git git config --global user.email 'networkagent@example.com'"
  args:
    chdir: /opt/london-cluster-repo

###############################################
# Master Branch
###############################################
- name: checkout master branch
  command: sudo -u git git checkout -B master
  args:
    chdir: /opt/london-cluster-repo

- name: push files to master branch
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/london-cluster-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - Readme.md
    - controlplanenetwork.yaml
    # - cpaddresses.yaml

- name: Create london cluster crd directory
  file:
    path: /opt/london-cluster-repo/crds
    state: directory
    owner: git
    group: git
    mode: 0775

- name: push crd files
  ansible.builtin.copy:
    src: "crds/"
    dest: "/opt/london-cluster-repo/crds/"
    owner: git
    group: git
    mode: '0644'

- name: push templated files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/london-cluster-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - graph.yaml

- name: add files to master london-cluster-repo
  command: sudo -u git git add .
  args:
    chdir: /opt/london-cluster-repo

- name: initial commit 
  command: sudo -u git git commit -m "initial commit"
  args:
    chdir: /opt/london-cluster-repo

- name: add remote repo
  command: sudo -u git git remote add origin https://{{ lookup('env', 'WEBAPPS_LOGIN') }}:{{ lookup('env', 'WEBAPPS_PWD') }}@{{external_ip_address}}:3000/networkagent/london-cluster.git
  args:
    chdir: /opt/london-cluster-repo

- name: push to master branch in repo
  command: sudo -u git git -c http.sslVerify=false push -u origin master
  args:
    chdir: /opt/london-cluster-repo

###############################################
# Network Function Branch
###############################################
- name: checkout networkfunction branch
  command: sudo -u git git checkout -B networkfunction
  args:
    chdir: /opt/london-cluster-repo

- name: push files to network function branch
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/london-cluster-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - amf.yaml
    - ausf.yaml
    - nrf.yaml
    - pcf.yaml
    - smf.yaml
    - udm.yaml
    - udr.yaml
    - webui.yaml

- name: push templated files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/london-cluster-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - mongodb.yaml

- name: add files to network function branch 
  command: sudo -u git git add .
  args:
    chdir: /opt/london-cluster-repo

- name: nf files commit
  command: sudo -u git git commit -m "add network function files"
  args:
    chdir: /opt/london-cluster-repo

- name: push to network function branch in repo
  command: sudo -u git git -c http.sslVerify=false push -u origin networkfunction
  args:
    chdir: /opt/london-cluster-repo

