---
- hosts: all
  become: true
  gather_facts: true
  vars:
    # Default values - minimal needed for status check
    network_driver: "bridge"

  tasks:
    - name: Display connected containers (brctl bridges)
      command: brctl show {{ network_name }}
      register: brctl_output
      ignore_errors: yes
  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted
