applySpecVersion: 1
spec:
  configSync:
    enabled: true
    # # If you don't have a source of truth yet, omit the
    # # following fields. You can configure them later.
    # sourceType: SOURCE_TYPE
    # sourceFormat: FORMAT
    # syncRepo: REPO
    # syncRev: REVISION
    # syncBranch: BRANCH
    # secretType: SECRET_TYPE
    # gcpServiceAccountEmail: EMAIL
    # metricsGcpServiceAccountEmail: METRICS_EMAIL
    # policyDir: DIRECTORY
    # preventDrift: PREVENT_DRIFT