---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site1-dev
spec:
  ipCidrRange: 10.10.0.0/24
  region: europe-west2
  description: Site1 Dev Network
  networkRef:
    name: site1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site1-prod
spec:
  ipCidrRange: 10.11.0.0/24
  region: europe-west2
  description: Site1 Prod Network
  networkRef:
    name: site1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site1
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-dev
spec:
  ipCidrRange: 10.20.0.0/24
  region: europe-west2
  description: site2-dev
  networkRef:
    name: site2
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-prod
spec:
  ipCidrRange: 10.21.0.0/24
  region: europe-west2
  description: site2-prod
  networkRef:
    name: site2
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site2
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site3-prod
spec:
  ipCidrRange: 10.50.0.0/24
  region: europe-west2
  description: site3-prod
  networkRef:
    name: site3
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site3
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false