############# Site 1 Dev ################ 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site1-dev
  labels: 
    customer: "Enterprise1"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site1-dev
  labels: 
    customer: "Enterprise1"
spec:
  ipCidrRange: 10.0.10.0/24
  region: europe-west2
  description: Site1 Dev Network
  networkRef:
    name: site1-dev
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site1-dev-ssh
  labels: 
    customer: "Enterprise1"
spec:
  allow:
    - protocol: tcp
      ports:
       - "22"
  networkRef:
    name: site1-dev
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - ssh
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site1-dev-allow-incoming
  labels: 
    customer: "Enterprise1"
spec:
  allow:
    - protocol: icmp
  networkRef:
    name: site1-dev
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - incoming
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: site1-dev-router
  labels: 
    customer: "Enterprise1"
spec:
  description: site1 router
  region: europe-west2
  networkRef:
    name: site1-dev
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: computerouternat-sample-forallsubnets
  labels: 
    customer: "Enterprise1"
spec:
  region: europe-west2
  routerRef:
    name: site1-dev-router
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES

############# Site 1 Prod ################ 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site1-prod
  labels: 
    customer: "Enterprise1"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site1-prod
  labels: 
    customer: "Enterprise1"
spec:
  ipCidrRange: 10.0.11.0/24
  region: europe-west2
  description: Site1 Prod Network
  networkRef:
    name: site1-prod
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site1-prod-allow-all
  labels: 
    customer: "Enterprise1"
spec:
  allow:
    - protocol: icmp
    - protocol: tcp
      ports:
        - "80"
        - "22"
        - "443"
  networkRef:
    name: site1-prod
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - all
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: site1-prod-router
  labels: 
    customer: "Enterprise1"
spec:
  description: site1 router
  region: europe-west2
  networkRef:
    name: site1-prod
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: site1-prod-nat
  labels: 
    customer: "Enterprise1"
spec:
  region: europe-west2
  routerRef:
    name: site1-prod-router
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES

############# Site 2 Dev ################ 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site2-dev
  labels: 
    customer: "Enterprise1"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-dev
  labels: 
    customer: "Enterprise1"
spec:
  ipCidrRange: 10.0.20.0/24
  region: europe-west2
  description: site2-dev
  networkRef:
    name: site2-dev
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site2-dev-allow-all
  labels: 
    customer: "Enterprise1"
spec:
  allow:
    - protocol: icmp
    - protocol: tcp
      ports:
        - "80"
        - "443"
        - "22"
  networkRef:
    name: site2-dev
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - all
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: site2-dev-router
  labels: 
    customer: "Enterprise1"
spec:
  description: site2 router
  region: europe-west2
  networkRef:
    name: site2-dev
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: site2-dev-nat
  labels: 
    customer: "Enterprise1"
spec:
  region: europe-west2
  routerRef:
    name: site2-dev-router
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES

############# Site 2 Prod ################ 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site2-prod
  labels: 
    customer: "Enterprise1"
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-prod
  labels: 
    customer: "Enterprise1"
spec:
  ipCidrRange: 10.0.21.0/24
  region: europe-west2
  description: site2-prod
  networkRef:
    name: site2-prod
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site2-prod-allow-all
  labels: 
    customer: "Enterprise1"
spec:
  allow:
    - protocol: icmp
    - protocol: tcp
      ports:
        - "80"
        - "22"
        - "443"
  networkRef:
    name: site2-prod
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - all
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: site2-prod-router
  labels: 
    customer: "Enterprise1"
spec:
  description: site2 prod router
  region: europe-west2
  networkRef:
    name: site2-prod
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: site2-prod-nat
  labels: 
    customer: "Enterprise1"
spec:
  region: europe-west2
  routerRef:
    name: site2-prod-router
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
