# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gitea-shared-storage
#   namespace: automation
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 200Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gitea-deployment
#   namespace: automation
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gitea
#   template:
#     metadata:
#       labels:
#         app: gitea
#     spec:
#       volumes:
#       - name: gitea-volume
#         persistentVolumeClaim:
#           claimName: gitea-shared-storage
#       containers:
#       - name: gitea-container
#         image: gitea/gitea:latest
#         ports:
#         - containerPort: 3000
#           name: gitea-web
#         - containerPort: 22
#           name: gitea-ssh
#         volumeMounts:
#         - mountPath: /data
#           name: gitea-volume
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gitea-lb-service
#   namespace: automation
# spec:
#   type: LoadBalancer
#   selector:
#     app: gitea
#   ports:
#   - name: web
#     protocol: TCP
#     port: 5000
#     targetPort: 3000

apiVersion: google.dev/v1
kind: Gitea
metadata:
  name: gitea
spec:
  nodes: