- name: delete compute for site
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeInstance
    namespace: automation
    name: '{{ vmname }}'

- name: delete external IP for site
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    namespace: automation
    kind: ComputeAddress
    name: '{{vmname}}-ip'
