- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Create site network
      import_role:
        name: addnetwork

    - name: Create site compute
      import_role:
        name: addcompute

    - name: Create site vpn
      import_role:
        name: addvpn

    # create route
