- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Subnetwork Instance
      kubernetes.core.k8s_info:
        api_version: compute.cnrm.cloud.google.com/v1beta1
        kind: ComputeSubnetwork
        name: '{{ subnetname }}'
        namespace: automation

