- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: install base apt packages
  ansible.builtin.apt:
    pkg:
      - gnupg-agent
      - apt-transport-https 
      - software-properties-common
    state: latest
    update_cache: true

- name: install pip dependencies
  ansible.builtin.pip:
    name:
      - docker 

- name: update the version of requests
  command: pip install requests==2.28.1

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: latest
    update_cache: true
