openapi: 3.0.3
info:
  title: Network Agent Tools
  description: |-
    These rest apis provide a set of endpoints that can query and create
    network connectivity services. 

    A set of available network connectivity services whose lifecycle can be 
    managed through this rest endpoint.

  version: 0.0.1
servers:
  - url: http://networktools-lb-service:8080/ui/
paths:
  /locations/{name}:
    get:
      summary: Retrive a set of network locations
      description: |-
        Return a set of Customer specific GCP networks and locations that can be connected together with 
        available connectivity services
      operationId: main.getCustomerLocations
      parameters:
        - name: name
          in: path
          description: A string representing the customer name
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
      responses:
        "200":
          description: successful operation
        "404":
          description: No locations found
        "400":
          description: Incorrect information provided
  /apps/{name}:
    get:
      summary: Retrive a set of IT applications running in each network location
      description: |-
        Return a set of Customer specific IT applications that are deployed to each network location
      operationId: main.getCustomerApplications
      parameters:
        - name: name
          in: path
          description: A string representing the customer name
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
      responses:
        "200":
          description: successful operation
        "404":
          description: No applications found
        "400":
          description: Incorrect information provided
  /definitions:
    get:
      summary: Retrive a set of network connectivity definitions
      description: |-
        Return a set of k8s CRDs that describe the available types of connetivity services available.

        Each CRD provides an OpenAPI schema with the information required to instantiate the service
      operationId: main.getServiceDefinitions
      responses:
        "200":
          description: successful operation
        "404":
          description: No definitions found
  /deployed/{name}:
    get:
      summary: Get the deployed connectivity services for this customer
      description: |-
        Get the connectivity services that have already been deployed for this customer
      operationId: main.getServices
      parameters:
        - name: name
          in: path
          description: A string representing the customer name
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
      responses:
        "200":
          description: successful operation
        "404":
          description: No deployed services found
        "400":
          description: Incorrect information provided
  /service:
    delete:
      summary: delete a deployed connectivity service
      operationId: main.deleteService
      parameters:
        - name: name
          in: query
          description: A string representing the name of the deployed connectivity service
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
        - name: kind
          in: query
          description: A string representing the kind of the connectivity service
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: PointToPointService
      responses:
        "200":
          description: successful request to delete an existing service
        "404":
          description: service does not exist
    post:
      summary: creates a request to for a new connectivity service
      description: |-
        Create a New Connectivity service.
      operationId: main.createService
      requestBody:
        x-body-name: payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Service"
            example:
              customerName: acme
              serviceInfo:
                kind: PointToPointService
                apiVersion: google.dev/v1
                spec:
                  interfaces:
                  - london-internal
                  - sydney-internal
      responses:
        "201":
          description: successful request to create new service received
        "400":
          description: Incorrect information provided
        "409":
          description: service with that name already exists
        "422":
          description: Schema validation errors 
  /test:
    delete:
      summary: delete a running connectivity test
      operationId: main.deleteTest
      parameters:
        - name: name
          in: query
          description: The name of the running connectivity test
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
      responses:
        "200":
          description: successful request to delete an test
        "404":
          description: test does not exist
    post:
      summary: creates a request for a new network connectivity test between two IT applications connected to customer locations
      description: |-
        Create a New network connectivity test.
      operationId: main.createTest
      requestBody:
        x-body-name: payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
            example:
              name: acme
              virtualmachines:
              - london-app1
              - sydney-app1
      responses:
        "201":
          description: successful request to create new service received
        "400":
          description: Incorrect information provided
        "409":
          description: test with that name already exists
        "422":
          description: Schema validation errors 
  /metrics:
    get:
      summary: retrieve performance metrics for a deployed connectivity service
      description: |-
        Return a set JSON performance metrics for the last period specified with the following JSONL schema
        [
          {"name": "data","type": "JSON","mode": "NULLABLE","description": "The data"},
          {"name": "subscription_name","type": "string","mode": "NULLABLE","description": "service name"},
          {"name": "attributes","type": "string","mode": "NULLABLE","description": "name of the vm"},
          {"name": "publish_time","type": "TIMESTAMP","mode": "NULLABLE","description": "time published"},
          {"name": "message_id","type": "string","mode": "NULLABLE","description": "name of nic reporting"}
        ]
      parameters:
        - name: name
          in: query
          description: The name of the deployed service
          required: true
          schema:
            type: string
          examples:
            Acme:
              value: acme
        - name: period
          in: query
          description: The period of time to collect performance metrics over in minutes
          required: true
          schema:
            type: integer
          examples:
            Acme:
              value: 10

      operationId: main.getServicePerformanceMetrics
      responses:
        "200":
          description: successful operation
        "404":
          description: No metrics found

components:
  schemas:
    Definition:
      type: object
      properties:
        crd:
          type: string
    Service:
      type: object
      properties:
        customerName:
          description: Name of the customer requesting the new service
          type: string
        serviceInfo:
          description: |-
            The type of the connectivity service to instantiate. This maps to the 
          type: object
          properties:
            kind:
              description: Kubernetes kind for the chosen connectivity service
              type: string
            apiVersion:
              description: Kubernetes apiVersion for the chosen connectivity service
              type: string
            spec:
              type: object
              description: |-
                Object describing the spec section of the CRD manifest for the chosen service type
                For example, for a PointToPoint connectivity service the string payload would look like as follows

                spec:
                  interfaces: # the "remote" customer subnets to connect
                    - london-internal
                    - sydney-internal
    Test:
      type: object
      properties:
        name:
          description: a name for the test
          type: string
        virtualmachines:
          description: IT applications to run the test to/from
          type: array
          items:
            type: string
          oneOf:
            - minItems: 2
              maxItems: 2

