edges:
  hosts:
    edge1: 
      ansible_host: 35.246.106.95 
      ansible_user: admin_briannaughton_altostrat_co 
      ansible_connection: ssh 
      ansible_ssh_private_key_file: ../google-compute
      tunnelSubnet: 192.168.1.0/24
      tunnelAddress: 192.168.1.1
      interface: site1-dev
      peer: edge2

    edge2:
      ansible_host: 34.147.213.36 
      ansible_user: admin_briannaughton_altostrat_co 
      ansible_connection: ssh 
      ansible_ssh_private_key_file: ../google-compute
      tunnelSubnet: 192.168.10.0/24
      tunnelAddress: 192.168.10.1
      interface: site2-dev
      peer: edge1

  vars:
    wgKeys:
      edge1:
        privateKey: KJ/HkhQJ8TrU40Nh3NDznxYO+6Ev0hFLbjJAn1wuMWg=
        publicKey: +b7Y2OeMKhyhTnsFBo/1wuw6oEXa/8JnXwSrp1JUwgs=
      edge2:
        privateKey: yN+/wI5idW6uVF5HAf28Vq6MEVoRgn5pI7ls8/xSaE4=
        publicKey: dKI4NcMWJj2uF97VztQEvhR+4aW5a7sBGB+y6wb9AXA=
