- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an existing Service object
      kubernetes.core.k8s_info:
        api_version: compute.cnrm.cloud.google.com/v1beta1
        kind: ComputeInstance
        name: '{{ edge_vm_name }}'
        namespace: automation
