- name: Create newyork directory
  file:
    path: /opt/newyork-repo
    state: directory
    owner: git
    group: git
    mode: 0775

- name: init git repo
  command: sudo -u git git init
  args:
    chdir: /opt/newyork-repo

- name: configure git user name
  command: "sudo -u git git config --global user.name 'Network Agent'"
  args:
    chdir: /opt/newyork-repo

- name: configure git email
  command: "sudo -u git git config --global user.email 'networkagent@example.com'"
  args:
    chdir: /opt/newyork-repo

###############################################
# Master Branch
###############################################
- name: checkout master branch
  command: sudo -u git git checkout -b master
  args:
    chdir: /opt/newyork-repo

- name: push readme files
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/newyork-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - Readme.md

- name: add readme to new york repo
  command: sudo -u git git add .
  args:
    chdir: /opt/newyork-repo

- name: initial commit 
  command: sudo -u git git commit -m "initial commit"
  args:
    chdir: /opt/newyork-repo

- name: add remote repo
  command: sudo -u git git remote add origin https://networkagent:{{ lookup('env', 'WEBAPPS_PWD') }}@{{ansible_host}}:3000/networkagent/newyork.git
  args:
    chdir: /opt/newyork-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin master
  args:
    chdir: /opt/newyork-repo

###############################################
# Location Branch
###############################################
- name: checkout dev branch
  command: sudo -u git git checkout -b location
  args:
    chdir: /opt/newyork-repo

- name: push readme files
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/newyork-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - Readme.md

- name: push templates files
  ansible.builtin.template:
    src: "newyork.yaml"
    dest: "/opt/newyork-repo/newyork.yaml"
    owner: git
    group: git
    mode: '0644'

- name: add files to location branch in new york repo
  command: sudo -u git git add .
  args:
    chdir: /opt/newyork-repo

- name: location files commit
  command: sudo -u git git commit -m "add location files"
  args:
    chdir: /opt/newyork-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin location
  args:
    chdir: /opt/newyork-repo

###############################################
# app Branch
###############################################
- name: checkout app branch
  command: sudo -u git git checkout -b app
  args:
    chdir: /opt/newyork-repo

- name: push templated files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/newyork-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - newyork-app.yaml
    - newyork.yaml

- name: add files to app branch in new york repo
  command: sudo -u git git add .
  args:
    chdir: /opt/newyork-repo

- name: app files commit
  command: sudo -u git git commit -m "add app files"
  args:
    chdir: /opt/newyork-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin app
  args:
    chdir: /opt/newyork-repo

###############################################
# Networkfunction Branch
###############################################
- name: checkout networkfunction branch
  command: sudo -u git git checkout -b networkfunction
  args:
    chdir: /opt/newyork-repo

- name: push files
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/newyork-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - newyork-ueransim.yaml
    - Readme.md

- name: push templates files
  ansible.builtin.template:
    src: "newyork.yaml"
    dest: "/opt/newyork-repo/newyork.yaml"
    owner: git
    group: git
    mode: '0644'

- name: add files to nf branch in new york repo
  command: sudo -u git git add .
  args:
    chdir: /opt/newyork-repo

- name: nf files commit
  command: sudo -u git git commit -m "add network function files"
  args:
    chdir: /opt/newyork-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin networkfunction
  args:
    chdir: /opt/newyork-repo

