- name: Create london repo directory
  file:
    path: /opt/london-repo
    state: directory
    owner: git
    group: git
    mode: 0775

- name: init git repo
  command: sudo -u git git init
  args:
    chdir: /opt/london-repo

- name: configure git user name
  command: "sudo -u git git config --global user.name 'Network Agent'"
  args:
    chdir: /opt/london-repo

- name: configure git email
  command: "sudo -u git git config --global user.email 'networkagent@example.com'"
  args:
    chdir: /opt/london-repo

###############################################
# Master Branch
###############################################
- name: checkout master branch
  command: sudo -u git git checkout -b master
  args:
    chdir: /opt/london-repo

- name: push files to master branch
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/london-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - Readme.md

- name: add readme to master network-services-repo
  command: sudo -u git git add .
  args:
    chdir: /opt/london-repo

- name: initial commit 
  command: sudo -u git git commit -m "initial commit"
  args:
    chdir: /opt/london-repo

- name: add remote repo
  command: sudo -u git git remote add origin https://networkagent:password123@{{ansible_host}}:3000/networkagent/london.git
  args:
    chdir: /opt/london-repo

- name: push to master branch in repo
  command: sudo -u git git -c http.sslVerify=false push -u origin master
  args:
    chdir: /opt/london-repo

###############################################
# location Branch
###############################################
- name: checkout location branch
  command: sudo -u git git checkout -b location
  args:
    chdir: /opt/london-repo

- name: push files to location branch
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/london-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - Readme.md

- name: push templated files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/london-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - london.yaml

- name: add files to london branch 
  command: sudo -u git git add .
  args:
    chdir: /opt/london-repo

- name: location files commit
  command: sudo -u git git commit -m "add location files"
  args:
    chdir: /opt/london-repo

- name: push to location branch in repo
  command: sudo -u git git -c http.sslVerify=false push -u origin location
  args:
    chdir: /opt/london-repo

###############################################
# Network Function Branch
###############################################
- name: checkout networkfunction branch
  command: sudo -u git git checkout -b networkfunction
  args:
    chdir: /opt/london-repo

- name: push files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/london-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - upf.yaml
    - Readme.md

- name: push templated files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/london-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
    - london-cluster.yaml
    - london.yaml

- name: add files to network function branch 
  command: sudo -u git git add .
  args:
    chdir: /opt/london-repo

- name: nf files commit
  command: sudo -u git git commit -m "add network function files"
  args:
    chdir: /opt/london-repo

- name: push to network function branch in repo
  command: sudo -u git git -c http.sslVerify=false push -u origin networkfunction
  args:
    chdir: /opt/london-repo

