# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-configmap
  labels:
    app: free5gc
data:
  pcfcfg.yaml: |
    info:
      version: 1.0.2
      description: PCF initial local configuration

    configuration:
      pcfName: PCF # the name of this PCF
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: pcf-npcf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 8000              # port used to bind the service
        tls: # the local path of TLS key
          pem: cert/pcf.pem # PCF TLS Certificate
          key: cert/pcf.key # PCF TLS Private key
      timeFormat: 2019-01-02 15:04:05 # time format of this PCF
      defaultBdtRefId: BdtPolicyId-   # BDT Reference ID, indicating transfer policies of background data transfer.
      nrfUri: http://nrf-nnrf:8000  # a valid URI of NRF
      serviceList:   # the SBI services provided by this PCF, refer to TS 29.507
        - serviceName: npcf-am-policy-control # Npcf_AMPolicyControl service
        - serviceName: npcf-smpolicycontrol   # Npcf_SMPolicyControl service
          suppFeat: 3fff # the features supported by Npcf_SMPolicyControl, name defined in TS 29.512 5.8-1, value defined in TS 29.571 5.2.2
        - serviceName: npcf-bdtpolicycontrol    # Npcf_BDTPolicyControl service
        - serviceName: npcf-policyauthorization # Npcf_PolicyAuthorization service
          suppFeat: 3    # the features supported by Npcf_PolicyAuthorization, name defined in TS 29.514 5.8-1, value defined in TS 29.571 5.2.2
        - serviceName: npcf-eventexposure       # Npcf_EventExposure service
        - serviceName: npcf-ue-policy-control   # Npcf_UEPolicyControl service
      mongodb:       # the mongodb connected by this PCF
        name: free5gc                  # name of the mongodb
        url: mongodb://mongodb:27017 # a valid URL of the mongodb
      locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located

    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    logger:
      enable: true # true or false
      level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      reportCaller: false # enable the caller report or not, value: true or false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-pcf
  labels:
    app: free5gc
    nf: pcf
    graph: "true"
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: pcf
    spec:
      initContainers:
      - name: wait-smf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: nrf-nnrf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the NRF; sleep 2; done;"]
      containers:
      - image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/pcf:latest
        name: pcf
        ports:
        - containerPort: 8000
        command: ["./pcf"]
        args: ["--config", "config/pcfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: pcf-volume
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: pcf-volume
        projected:
          sources:
          - configMap:
              name: pcf-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: pcf-npcf
  labels:
    app: free5gc
    nf: pcf
spec:
  ports:
    - port: 8000
  selector:
    app: free5gc
    nf: pcf
