- name: Get an interface cidr
  kubernetes.core.k8s_info:
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeSubnetwork
    name: '{{ interface }}'
    namespace: automation
  register: k8s_subnet

- set_fact:
    interface_cidr: "{{ k8s_subnet['resources'][0]['spec']['ipCidrRange'] }}"

- debug:
    msg: "CIDR for {{ interface }} is {{ interface_cidr }}"

- debug:
    msg: "{{ ansible_facts[item]['ipv4']}}"
  loop: "{{ansible_interfaces}}"

- debug:
    set_fact: 
      defaultInterface: "{{item}}"
  loop: "{{ansible_interfaces}}"
  when: ansible_facts[item]['ipv4']['network']+'/'+ansible_facts[item]['ipv4']['netmask'] | ansible.utils.ipaddr('net') == interface_cidr

- debug:
    var: defaultInterface

# - name: Get Peer Instance
#   kubernetes.core.k8s_info:
#     api_version: compute.cnrm.cloud.google.com/v1beta1
#     kind: ComputeInstance
#     name: '{{ peer }}'
#     namespace: automation
#   register: k8s_peer

# - set_fact:
#     peer_network: "{{ item['accessConfig'][0]['natIpRef']['name'] }}"
#   loop: "{{k8s_peer['resources'][0]['spec']['networkInterface']}}"
#   when: "'accessConfig' in item"

# - debug:
#     var: peer_network

# - name: Get Peer External IP
#   kubernetes.core.k8s_info:
#     api_version: compute.cnrm.cloud.google.com/v1beta1
#     kind: ComputeAddress
#     name: '{{ peer_network }}'
#     namespace: automation
#   register: k8s_peer_address

# - set_fact:
#     peer_ip_address: "{{k8s_peer_address['resources'][0]['spec']['address']}}"

# - debug:
#     var: peer_ip_address