- hosts: wait
  tasks:
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      ansible.builtin.wait_for:
        port: 22
        host: 34.147.168.80
        search_regex: OpenSSH
        delay: 10
      connection: local    

- hosts: edges
  tasks:

    - name: check if vyos exists
      ansible.builtin.stat:
        path: /opt/vyos
      register: vyos_exists

    - name: Build VyOS image if it does not exist
      import_role:
        name: install
      when: vyos_exists.stat.isdir is not defined