apiVersion: google.dev/v1
kind: WireguardAppliance
metadata:
  name: london-vpn
spec:
  vmname: london-vpn
  tunnelSubnet: 192.168.1.0/24
  tunnelAddress: 192.168.1.1/24
  allowedInterface: newyork-internal
  peer: newyork-vpn
