apiVersion: network.example.com/v1
kind: Monitoring
metadata:
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: monitoring-sample
spec:
  service: vpnservice-sample
