apiVersion: google.dev/v1
kind: ConnectivityService
metadata:
  name: vpnservice-sample
spec:
  type: site-to-site
  name: test-vpn
  vpcs:
    - site1-dev
    - site2-dev
  rules:
    - protocol: tcp
      ports:
        - 80
