apiVersion: network.example.com/v1
kind: ConnectivityService
metadata:
  name: vpnservice-sample
spec:
  type: wireguard
  name: test-vpn
  sourceSubnets:
    - site1-dev
  targetSubnets:
    - site2-dev
