---
- name: show stuff
  debug: 
    msg: name of the edge virtual machine CR = {{ edgemachine}}

# get the Object for the vm
# get the ip address for the VM
# create a dynamic host with the IP address
- name: Add a host alias that we reach through a tunnel (Ansible 1.9 and older)
  ansible.builtin.add_host:
    hostname: '{{ new_ip }}'
    ansible_ssh_host: '{{ inventory_hostname }}'
    ansible_ssh_port: '{{ new_port }}'
# install if needed
# do configure