- name: delete compute network
  kubernetes.core.k8s:
    state: absent
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeNetwork
    name: '{{sitename}}-external'

- name: delete subnetwork
  kubernetes.core.k8s:
    state: absent
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeSubnetwork
    name: '{{sitename}}-external'

- name: delete router
  kubernetes.core.k8s:
    state: absent
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeRouter
    name: '{{sitename}}-external-router'

- name: delete NAT
  kubernetes.core.k8s:
    state: present
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeRouterNAT
    name: '{{sitename}}-external-nat'

- name: delete wireguard rule
  kubernetes.core.k8s:
    state: absent
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeFirewall
    name: '{{sitename}}-external-wg'

- name: delete ssh rule
  kubernetes.core.k8s:
    state: absent
    apiVersion: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeFirewall
    name: '{{sitename}}-external-ssh'
