
- name: delete subnetwork
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeSubnetwork
    namespace: automation
    name: '{{sitename}}'

- name: delete router
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeRouter
    name: '{{sitename}}-router'
    namespace: automation

- name: delete NAT
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeRouterNAT
    namespace: automation
    name: '{{sitename}}-nat'

- name: delete wireguard rule
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeFirewall
    namespace: automation
    name: '{{sitename}}-wg'

- name: delete ssh rule
  kubernetes.core.k8s:
    state: absent
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeFirewall
    namespace: automation
    name: '{{sitename}}-ssh'

- name: delete compute network
  kubernetes.core.k8s:
    state: absent
    # wait for the network to be deleted before completing. All 
    # dependencies above must be complete before this can be deleted
    wait: yes
    api_version: compute.cnrm.cloud.google.com/v1beta1
    kind: ComputeNetwork
    namespace: automation
    name: '{{sitename}}'
