apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessionmanagementfunctions.google.dev
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: SessionManagementFunction
    plural: sessionmanagementfunctions
    singular: sessionmanagementfunction
    shortNames:
      - smf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName: 
                  description: The name of the cluster to deploy to
                  type: string
                upf:
                  description: The name of the UPF (just one for now)
                  type: object
                  properties:
                    name:
                      description: name of the upf
                      type: string
                    namespace:
                      description: namespace of upf
                      type: string
                dnn:
                  description: internet network
                  type: object
                  properties:
                    cidr:
                      type: string
                    static_cidr:
                      type: string
                    gateway_address:
                      type: string
                    destination_ip:
                      type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true