# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshservices.google.dev
  labels:
    type: networkservices
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: MeshService
    plural: meshservices
    singular: meshservice
    shortNames:
      - mesh
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            This connectivity service creates a wireguard vpn mesh between three to 10 GCP VPC locations.
            All locations will be able to route traffic to each other. 
          properties:
            spec:
              type: object
              properties:
                interfaces:
                  description: |
                    Between three and ten VPC Subnetwork locations to be connected together with a mesh VPN.

                    There must be no overlapping IP address ranges across each of the locations.
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        description: the name of the network interface
                        type: string
                  oneOf:
                    - minItems: 2
                      maxItems: 10
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true