# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wireguardappliances.google.dev
  labels:
    type: connectivityresource
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: WireguardAppliance
    plural: wireguardappliances
    singular: wireguardappliance
    shortNames:
      - wg
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceInterface: 
                  description: The network interface to bind this wireguard appliance instance to
                  type: object
                  properties:
                    name: 
                      description: The k8s network name
                      type: string
                    namespace:
                      description: the namespace the network is in
                      type: string
                tunnelSubnet:
                  description: The CIDR for the wireguard tunnel virtual nic.
                  type: string
                tunnelAddress:
                  description: The tunnel ip address assigned to this virtual appliance nic.
                  type: string
                keys:
                  description: this wireguard instance's public and private keys
                  type: object
                  properties:
                    public:
                      description: public keys
                      type: string
                    private:
                      description: public keys
                      type: string
                peers:
                  description: array of wireguard appliance peers and the allowed networks from each instance
                  type: array
                  oneOf:
                    - minItems: 1
                      maxItems: 10
                  items:
                    type: object
                    properties:
                      peerName:
                        description: The name of the other wireguard appliance to connect this instance to.
                        type: string
                      allowedInterface:
                        description: The name of the computesubnetwork that is reachable from the peer wireguard appliance
                        type: object
                        properties:
                          name: 
                            description: name of the interface
                            type: string
                      keys:
                        description: the peer wireguard instance's public and private keys
                        type: object
                        properties:
                          public:
                            description: public keys
                            type: string
                          private:
                            description: public keys
                            type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true