apiVersion: google.dev/v1
kind: MeshService
metadata:
  name: meshservice1
  labels:
    customer: acme
    graph: "true"
spec:
  interfaces: # the "remote" customer subnets to connect
    - dublin
    - singapore
    - newyork
