steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-west1-docker.pkg.dev/free5gc-384814/networkagent/networkagent:1.0 .
  automapSubstitutions: true
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker push europe-west1-docker.pkg.dev/free5gc-384814/networkagent/networkagent:1.0
images:
  - 'europe-west1-docker.pkg.dev/free5gc-384814/networkagent/networkagent:1.0'