- name: Check download
  ansible.builtin.stat:
    path: /opt/node_exporter-1.8.2.linux-amd64.tar.gz
  register: download

- name: download node exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /opt/node_exporter-1.8.2.linux-amd64.tar.gz
    force_basic_auth: yes
  when: not download.stat.exists 

- name: unzip node exporter\
  ansible.builtin.unarchive:
    src: /opt/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
  when: not download.stat.exists 

- name: run node exporter
  shell: nohup /opt/node_exporter-1.8.2.linux-amd64/node_exporter  </dev/null >/dev/null 2>&1 &