- name: Create core directory
  file:
    path: /opt/core-repo
    state: directory
    owner: git
    group: git
    mode: 0775

- name: init git repo
  command: sudo -u git git init
  args:
    chdir: /opt/core-repo

- name: configure git user name
  command: "sudo -u git git config --global user.name 'Network Agent'"
  args:
    chdir: /opt/core-repo

- name: configure git email
  command: "sudo -u git git config --global user.email 'networkagent@example.com'"
  args:
    chdir: /opt/core-repo

###############################################
# Skeleton Master Branch
###############################################
- name: checkout master branch
  command: sudo -u git git checkout -b master
  args:
    chdir: /opt/core-repo

- name: push readme.md to master branch
  ansible.builtin.copy:
    src: Readme.md
    dest: /opt/core-repo/Readme.md
    owner: git
    group: git
    mode: '0644'

- name: add readme to master branch in core-repo
  command: sudo -u git git add .
  args:
    chdir: /opt/core-repo

- name: initial commit to master
  command: sudo -u git git commit -m "initial commit"
  args:
    chdir: /opt/core-repo

- name: add remote repo
  command: sudo -u git git remote add origin https://networkagent:password123@{{ansible_host}}:3000/networkagent/core.git
  args:
    chdir: /opt/core-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin master
  args:
    chdir: /opt/core-repo

###############################################
# NetworkFunction branch
###############################################
- name: checkout networkfunction branch
  command: sudo -u git git checkout -b networkfunction
  args:
    chdir: /opt/core-repo

- name: push readme.md to vpn branch
  ansible.builtin.copy:
    src: Readme.md
    dest: /opt/core-repo/Readme.md
    owner: git
    group: git
    mode: '0644'

- name: push mesh
  ansible.builtin.copy:
    src: meshservice1.yaml
    dest: /opt/core-repo/meshservice1.yaml
    owner: git
    group: git
    mode: '0644'

- name: add mesh to vpn core-repo
  command: sudo -u git git add .
  args:
    chdir: /opt/core-repo

- name: mesh commit to vpn
  command: sudo -u git git commit -m "add mesh"
  args:
    chdir: /opt/core-repo

- name: push vpn to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin networkfunction
  args:
    chdir: /opt/core-repo

