set interfaces ethernet ens4 address dhcp
set interfaces ethernet ens4 description 'OUTSIDE'
set service https api
set service https listen-address 10.10.0.2
set service https port 443
set service https api debug
set service https api keys id theid key thepass
set firewall group interface-group LAN interface ens4
# set firewall ipv4 name MGMT rule 10 action ‘accept’
# set firewall ipv4 name MGMT rule 10 protocol ‘tcp’
# set firewall ipv4 name MGMT rule 10 destination port '443'
# set firewall ipv4 input filter rule 50 action 'accept'
# set firewall ipv4 input filter rule 50 source address 127.0.0.0/8
set firewall ipv4 name MGMT rule 15 action 'accept'
set firewall ipv4 name MGMT rule 15 inbound-interface group 'LAN'
set firewall ipv4 input filter rule 50 action 'accept'
set firewall ipv4 input filter rule 50 source address 127.0.0.0/8