apiVersion: google.dev/v1
kind: EdgeAppliance
metadata:
  name: edgeappliance-sample
spec:
  edgevm: edge1
  service:
    type: tunnel
    vendor: openvpn
    name: test-vpn
    secret: some-secret
    sourceSubnets:
      - site1-dev
      - site1-prod
    targetSubnets:
      - site2-dev
      - site2-prod
    peerEdge:
      - edge2