---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site1-external-subnet
spec:
  ipCidrRange: 10.100.0.0/24
  region: europe-west2
  description: Site1 External Network
  networkRef:
    name: site1-external
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site1-external
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false