# Install prometheus in VM
- hosts: all
  become: True
  gather_facts: False
  tasks:

  - name: Check if prometheus already downloaded
    ansible.builtin.stat:
      path: /opt/prometheus-2.54.0.linux-amd64.tar.gz
    register: download

  - name: Downloading prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.54.0/prometheus-2.54.0.linux-amd64.tar.gz
      dest: /opt/prometheus-2.54.0.linux-amd64.tar.gz
      force_basic_auth: yes
    when: not download.stat.exists 

  - name: Unzip prometheus
    ansible.builtin.unarchive:
      src: /opt/prometheus-2.54.0.linux-amd64.tar.gz
      dest: /opt
      remote_src: yes
    when: not download.stat.exists 

  - name: Start prometheus
    raw: nohup /opt/prometheus-2.54.0.linux-amd64/prometheus --config.file=/opt/config.yaml </dev/null >/dev/null 2>&1 &

  - name: install BQ publisher
    import_role:
      name: publish

  # - name: install grafana
  #   import_role:
  #     name: grafana