# Install prometheus in VM
- hosts: all
  become: True
  gather_facts: False
  tasks:

  - name: Check if prometheus already downloaded
    ansible.builtin.stat:
      path: /opt/prometheus-2.54.0.linux-amd64.tar.gz
    register: download

  - name: Downloading prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.54.0/prometheus-2.54.0.linux-amd64.tar.gz
      dest: /opt/prometheus-2.54.0.linux-amd64.tar.gz
      force_basic_auth: yes
    when: not download.stat.exists 

  - name: Unzip prometheus
    ansible.builtin.unarchive:
      src: /opt/prometheus-2.54.0.linux-amd64.tar.gz
      dest: /opt
      remote_src: yes
    when: not download.stat.exists 

  - name: install BQ publisher
    import_role:
      name: publish

  - name: Check if grafana already downloaded
    ansible.builtin.stat:
      path: /opt/grafana-11.1.4.linux-amd64.tar.gz
    register: download

  - name: Downloading grafana
    ansible.builtin.get_url:
      url: https://dl.grafana.com/oss/release/grafana-11.1.4.linux-amd64.tar.gz
      dest: /opt/grafana-11.1.4.linux-amd64.tar.gz
      force_basic_auth: yes
    when: not download.stat.exists 

  - name: Unzip grafana
    ansible.builtin.unarchive:
      src: /opt/grafana-11.1.4.linux-amd64.tar.gz
      dest: /opt
      remote_src: yes
    when: not download.stat.exists 

  - name: kill grafana if it is running
    raw: pkill grafana
    ignore_errors: True

  - name: Run grafana server
    raw: nohup /opt/grafana-v11.1.4/bin/grafana server </dev/null >/dev/null 2>&1 &

