########################################################
# Get API token
########################################################
- name: authenticate with gitea
  command: "curl -H 'Content-Type: application/json' -d '{\"name\":\"root-repo\", \"scopes\":[\"write:repository\", \"write:user\", \"write:admin\"]}' -u networkagent:password123 https://{{ansible_host}}:3000/api/v1/users/networkagent/tokens --insecure"
  register: result

- set_fact:
    token_result: "{{ result.stdout | from_json }}"

- debug:
    var: token_result

########################################################
# Create Repos
########################################################
- name: create root-repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"root-repo\"}' --insecure"
  when: token_result.sha1 is defined

- name: create london repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"london\"}' --insecure"
  when: token_result.sha1 is defined

- name: create dublin repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"dublin\"}' --insecure"
  when: token_result.sha1 is defined

- name: create newyork repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"newyork\"}' --insecure"
  when: token_result.sha1 is defined

- name: create core repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"core\"}' --insecure"
  when: token_result.sha1 is defined

- name: create london cluster repo
  command: "curl -k  -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/repos -d '{\"name\": \"london-cluster\"}' --insecure"
  when: token_result.sha1 is defined

########################################################
# NetworkAgent SSH Key
########################################################
- name: create ssh key for networkagent user
  command: "curl -k -H 'Content-Type: application/json'  -H 'Authorization: token {{ token_result['sha1'] }}' https://{{ansible_host}}:3000/api/v1/user/keys -d '{\"title\": \"NetworkAgent key\", \"key\": \"{{ GOOGLE_SSH_KEY }}\"}' --insecure"
  register: out
  when: token_result.sha1 is defined
