- name: Create a Service object from an inline definition
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: compute.cnrm.cloud.google.com/v1beta1
      kind: ComputeRoute
      metadata:
        name: '{{sitename}}-dev-route'
      spec:
        description: "'{{sitename}} Compute route"
        destRange: 10.0.20.0/24
        networkRef:
          name: '{{sitename}}-dev-route'
        priority: 100
        nextHopIp: 10.0.10.4