- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: install base apt packages
  ansible.builtin.apt:
    pkg:
      - gnupg-agent
      - apt-transport-https 
      - software-properties-common
    state: latest
    update_cache: true

- name: install pip dependencies
  ansible.builtin.pip:
    name:
      - docker 

- name: update the version of requests
  command: pip install requests==2.28.1

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: latest
    update_cache: true

- name: install headers matching kernel
  apt:
    pkg:
    - linux-headers-{{ansible_kernel}}

- name: create /opt/gtp5
  file:
    path: /opt/gtp5
    state: directory
    mode: '0777' 

- name: git checkout from gtp5
  ansible.builtin.git:
    repo: https://github.com/free5gc/gtp5g.git
    dest: /opt/gtp5

- name: Build and install gtp module
  ansible.builtin.shell: |
    make clean
    make
    make install
  args:
    chdir: /opt/gtp5

- name: download networkagent.json
  ansible.builtin.copy: 
    src: /operator/networkagent.json
    dest: /opt

- name: authenticate with the artefact repo
  raw: "cat /opt/networkagent.json | docker login -u _json_key --password-stdin https://{{GOOGLE_REGION}}-docker.pkg.dev"

# - name: docker pull upf
#   command: "docker pull {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/upf:latest"
