apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: edge1
spec:
  machineType: e2-medium
  zone: europe-west2-a
  bootDisk:
    autoDelete: false
    initializeParams:
      sourceImageRef:
        external: https://www.googleapis.com/compute/v1/projects/free5gc-384814/global/machineImages/vyos-edge
  networkInterface:    
    - subnetworkRef:
        name: site1-dev
  canIpForward: true
