# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0
info:
  title: Text2SQL API
  description: API for converting natural language text into SQL queries
  version: 1.0.0

servers:
  - url: https://cx-text2sql-aebg4pjsvq-uc.a.run.app   

paths:
  /:
    post:
      summary: Translate text to SQL
      description: Takes a natural language query and dataset name, returns SQL and results
      operationId: sql_generation 
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Text2SQLRequest' 
      responses:
        '200':
          description: Successful translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Text2SQLResponse'
        # ... other error responses 

components:
  schemas:
    Text2SQLRequest:
      type: object
      properties:
        sessionInfo:
          type: object
          properties:
            parameters:
              type: object
              properties:
                query:
                  type: string
                dataset:
                  type: string
    Text2SQLResponse:
      type: object
      properties:
        fulfillmentResponse: 
          type: object
          properties:
            messages:
              type: array
              items:
                type: object
                properties:
                  text:
                    type: object
                    properties:
                      text:
                        type: array
                        items:
                          type: string # For text responses
        sessionInfo:
          type: object
          properties:
            parameters:
              type: object
              properties:
                text2sql:
                  type: object
                  properties:
                    results:
                      type: array
                      items:
                        type: array
                        items:
                          type: string
                    status:
                      type: string
                    sql: 
                      type: string