openapi: 3.0.3
info:
  title: Network Agent Tools
  description: |-
    These rest apis provide a set of tools that can query and create
    network connectivity services. 
  version: 0.0.1
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /locations/customername:
    get:
      summary: Retrive a set of network locations
      description: Return a set of Customer specific GCP Subnetworks that can be connected over a connectivity service tunnel
      operationId: getLocations
      parameters:
        - name: status
          in: query
          description: A string representing the customer name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
  /services/{name}:
    post:
      summary: creates a request to create a new connectivity service
      description: Create a New Connectivity Service between two GCE Subnetwork Locations
      operationId: createService
      parameters:
        - name: name
          in: path
          description: name of the customer
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref : "#/components/schemas/Service"
      responses:
        '201':
          description: successful request to create new service received
components:
  schemas:
    Service:
      type: object
      properties:
        name:
          type: string
        locations:
          type: array
          items:
            type: string
  requestBodies:
    Service:
      description: Service Object to create a connectivity service
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Service'
