---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: london
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: london-internal
spec:
  ipCidrRange: 10.0.50.0/24
  region: europe-west2
  description: london Network
  networkRef:
    name: london
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: london-router
spec:
  description: london router
  region: europe-west2
  networkRef:
    name: london
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: 'london-nat'
spec:
  region: europe-west2
  routerRef:
    name: london-router
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: london-allowed
spec:
  allow:
    - protocol: tcp
      ports:
       - "22"
       - "80"
    # - protocol: icmp
  networkRef:
    name: london
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - london-allowed
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: london-app1
spec:
  machineType: e2-small
  zone: europe-west2-a
  bootDisk:
    initializeParams:
      size: 50
      type: pd-ssd
      sourceImageRef:
        external: ubuntu-os-cloud/ubuntu-2204-lts
  networkInterface:
    - subnetworkRef:
        name: london-internal
    - subnetworkRef:
        external: https://www.googleapis.com/compute/v1/projects/free5gc-384814/regions/europe-west2/subnetworks/mgmt-subnet
  canIpForward: true
  # metadataStartupScript: "sudo apt-get update; sudo apt-get install -yq python3-pip"
  metadata:
    - key: ssh-keys
      value: admin_briannaughton_altostrat_co:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN57YanONs2q/Eor4Tjv1NRhBGrB59vPFAMZbvlOVtkX briannaughton
  tags:
    - london-allowed
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: london-app2
spec:
  machineType: e2-small
  zone: europe-west2-a
  bootDisk:
    initializeParams:
      size: 50
      type: pd-ssd
      sourceImageRef:
        external: ubuntu-os-cloud/ubuntu-2204-lts
  networkInterface:
    - subnetworkRef:
        name: london-internal
    - subnetworkRef:
        external: https://www.googleapis.com/compute/v1/projects/free5gc-384814/regions/europe-west2/subnetworks/mgmt-subnet
  canIpForward: true
  # metadataStartupScript: "sudo apt-get update; sudo apt-get install -yq python3-pip"
  metadata:
    - key: ssh-keys
      value: admin_briannaughton_altostrat_co:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN57YanONs2q/Eor4Tjv1NRhBGrB59vPFAMZbvlOVtkX briannaughton
  tags:
    - london-allowed
