apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRoute
metadata:
  name: newyork-route
spec:
  description: "A sample compute route"
  destRange: 10.0.10.0/24
  networkRef:
    name: newyork-route
  priority: 100
  nextHopIp: 10.0.20.4