apiVersion: google.dev/v1
kind: ConnectivityService
metadata:
  name: vpnservice1
  labels:
    customer: acme
spec:
  type: site-to-site
  interfaces: # the "remote" subnets to connect
    - london-internal
    - sydney-internal
