---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-external
spec:
  ipCidrRange: 10.200.0.0/24
  region: europe-west2
  description: Site2 External Network
  networkRef:
    name: site2-external
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site2-external
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: site2-external-wg
spec:
  allow:
    - protocol: udp
      ports:
       - "5180"
  networkRef:
    name: site2-external
  direction: INGRESS
  sourceRanges:
    - 0.0.0.0/0
  targetTags:
    - wireguard