---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: site2-external-subnet
spec:
  ipCidrRange: 10.200.0.0/24
  region: europe-west2
  description: Site2 External Network
  networkRef:
    name: site2-external
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: site2-external
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false