---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "automation"
  name: networkoperator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkoperator-role-cluster
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [google.dev]
    resources: [connectivityservices, wireguardappliances]
    verbs: [list, get, create, watch, patch, delete]

  # Application: other resources managed.
  - apiGroups: [compute.cnrm.cloud.google.com]
    resources: [computenetworks, computeaddresses, computesubnetworks, computeinstances, computerouters, computerouternats, computefirewalls]
    verbs: [list, get, create, watch, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: networkoperator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: networkoperator-role-cluster
subjects:
  - kind: ServiceAccount
    name: networkoperator-account
    namespace: "automation"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkoperator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: networkoperator
  template:
    metadata:
      labels:
        application: networkoperator
    spec:
      serviceAccountName: networkoperator-account
      containers:
      - name: networkoperator
        image: europe-west2-docker.pkg.dev/free5gc-384814/networkagent/networkoperator:latest
        imagePullPolicy: Always
        env:
        - name: BASEDIR
          value: "/operator"
        - name: PROJECT
          value: "free5gc-384814"
        - name: REGION
          value: "europe-west2"
        - name: ZONE
          value: "europe-west2-a"
