apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkoperator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: networkoperator
  template:
    metadata:
      labels:
        application: networkoperator
    spec:
      containers:
      - name: networkoperator
        image: europe-west2-docker.pkg.dev/free5gc-384814/networkagent/networkoperator:latest