- hosts: all
  become: True
  gather_facts: False
  tasks:

  - name: run install
    import_role:
      name: install

  # - name: install ops agent
  #   import_role:
  #     name: opsagent

  - name: run wireguard
    become: True
    ansible.builtin.systemd_service:
      state: restarted
      enabled: true
      name: wg-quick@wg0
