# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: google.dev/v1
kind: UERanSIM
metadata:
  name: cellsite1
  labels:
    graph: "true"
    monitor: "true"
spec:
  cellid: "0x000000011"
  interface: 
    name: cellsite1
    namespace: cellsite1
  controlplane:
    name: controlplane
    namespace: core
  ue:     
    imsi: "208930000000002"
    plmnId: "20893"