- hosts: all
  become: True
  gather_facts: False
  tasks:

    - name: install Gitea
      import_role:
        name: install

    - name: create gitea repos
      import_role:
        name: create-gitea-repos
    
    - name: london-repo
      import_role:
        name: london-repo

    - name: london-cluster-repo
      import_role:
        name: london-cluster-repo

    - name: dublin-repo
      import_role:
        name: dublin-repo

    - name: newyork-repo
      import_role:
        name: newyork-repo

    - name: core-repo
      import_role:
        name: core-repo

    - name: root-repo
      import_role:
        name: rootrepo
